export const FETCH_USER = 'FETCH_USER';
// export const SERVER_ERROR = "SERVER_ERROR";
export const CLIENT_ERRORS = 'CLIENT_ERRORS';
export const FETCH_MY_PROPERTIES = 'FETCH_MY_PROPERTIES';
export const SAVE_PROPERTY = 'SAVE_PROPERTY';
export const MAKE_PAYMENT_PROPERTY = 'MAKE_PAYMENT_PROPERTY';
